services:
    srt-live-transmit:
        build:
            context: .
            dockerfile: Dockerfile.lt
        command: ["srt://:8888?mode=listener&latency=10", "srt://srt-ffplay:9999?mode=caller&latency=10"]
        restart: unless-stopped
        ports:
            - 8888:8888/udp
        depends_on:
            - srt-ffplay

    srt-ffplay:
        build:
            context: .
            dockerfile: Dockerfile.ff

        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - ${XAUTHORITY}:/root/.Xauthority:ro
        devices:
            - /dev/dri:/dev/dri
        command:
            [
                "-noborder",
                "-an",
                "-fflags",
                "nobuffer",
                "-flags",
                "low_delay",
                "-framedrop",
                "-strict",
                "experimental",
                "-probesize",
                "32",
                "-analyzeduration",
                "0",
                "srt://:9999?mode=listener&latency=10",
            ]
        restart: unless-stopped
