services:
    nginx-rtmp:
        image: tiangolo/nginx-rtmp # lightweight nginx with rtmp
        ports:
            - "1935:1935" # RTMP port
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        restart: unless-stopped

    ffplay:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - nginx-rtmp
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
            - ${XAUTHORITY}:/root/.Xauthority:ro
        devices:
            - /dev/dri:/dev/dri
        command:
            [
                "-noborder",
                "-fflags",
                "nobuffer",
                "-flags",
                "low_delay",
                "-framedrop",
                "-strict",
                "experimental",
                "rtmp://nginx-rtmp/live/stream",
            ]
        restart: unless-stopped
        ipc: host
